---
apiVersion: v1
kind: Service
metadata:
  name: api-to-kubernetes-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 3333
  selector:
    name: api-to-kubernetes
